# config.py
ALPACA_API_KEY = 'PK0YKTTK8XSCCTDM1208'
ALPACA_API_SECRET = 'HosawmfTrlhG0cfEWV39gBtmXaUneXMOEYZA6bTE'
# Feb account
#ALPACA_API_KEY = 'PKIBD6L8HYJI1TMO9ZVZ'
#ALPACA_API_SECRET = 'RG2ieuMUECxkwO1Thvj9BQDwUeevGGUvw99RQfgT'
ALPACA_BASE_URL = 'https://paper-api.alpaca.markets'

ALPHA_VANTAGE_API_KEY = 'XD68QWVIH31JDTGD'

# Trading Parameters
REST_API_TIMEOUT = 10
MAX_POSITIONS = 5
RISK_PER_TRADE = 0.02